export const data = {
  incomes: [
    {
      id: 1,
      date: 'May 11th',
      source: 'Salary',
      amount: 2200,
      category: 'Regular',
      description: 'Monthly salary',
      badgeColor: '#96ceb4',
    },
    {
      id: 2,
      date: 'May 11th',
      source: 'Deposit Revenue',
      amount: 350,
      category: 'Regular',
      description: 'Bank revenue',
      badgeColor: '#ffeead',
    },
    {
      id: 3,
      date: 'May 11th',
      source: 'Freelance',
      amount: 700,
      category: 'Non-Regular',
      description: 'Getting payment from the customer',
      badgeColor: '#ffcc5c',
    },
    {
      id: 4,
      date: 'May 11th',
      source: 'Salary',
      amount: 2200,
      category: 'Regular',
      description: 'Monthly salary',
      badgeColor: '#96ceb4',
    },
    {
      id: 5,
      date: 'May 11th',
      source: 'Deposit Revenue',
      amount: 350,
      category: 'Regular',
      description: 'Bank revenue',
      badgeColor: '#ffeead',
    },
    {
      id: 6,
      date: 'May 11th',
      source: 'Freelance',
      amount: 700,
      category: 'Non-Regular',
      description: 'Getting payment from the customer',
      badgeColor: '#ffcc5c',
    },
    {
      id: 7,
      date: 'May 11th',
      source: 'Salary',
      amount: 2200,
      category: 'Regular',
      description: 'Monthly salary',
      badgeColor: '#96ceb4',
    },
    {
      id: 8,
      date: 'May 11th',
      source: 'Deposit Revenue',
      amount: 350,
      category: 'Regular',
      description: 'Bank revenue',
      badgeColor: '#ffeead',
    },
    {
      id: 9,
      date: 'May 11th',
      source: 'Freelance',
      amount: 700,
      category: 'Non-Regular',
      description: 'Getting payment from the customer',
      badgeColor: '#ffcc5c',
    },
    {
      id: 10,
      date: 'May 11th',
      source: 'Salary',
      amount: 2200,
      category: 'Regular',
      description: 'Monthly salary',
      badgeColor: '#96ceb4',
    },
    {
      id: 11,
      date: 'May 11th',
      source: 'Deposit Revenue',
      amount: 350,
      category: 'Regular',
      description: 'Bank revenue',
      badgeColor: '#ffeead',
    },
    {
      id: 12,
      date: 'May 11th',
      source: 'Freelance',
      amount: 700,
      category: 'Non-Regular',
      description: 'Getting payment from the customer',
      badgeColor: '#ffcc5c',
    }
  ],
  expenses: [
    {
      id: 1,
      date: 'May 11th',
      merchant: 'Bank of America',
      amount: 28000,
      image: '',
      category: 'Car',
      description: 'Buying a new car',
      badgeColor: '#fbefcc',
    },
    {
      id: 2,
      date: 'May 11th',
      merchant: 'Amazon.com',
      amount: 3600,
      image: '',
      category: 'Equipment',
      description: 'Buying a laptop',
      badgeColor: '#f9ccac',
    },
    {
      id: 3,
      date: 'May 11th',
      merchant: 'United Airlines',
      amount: 1500,
      image: '',
      category: 'Travel',
      description: 'Booking a fly tickets',
      badgeColor: '#f4a688',
    },
  ],
  totalIncome: 3250,
  totalExpenses: 33100,
  profile: {
    user: {
      firstName: 'John',
      lastName: 'Doe',
      email: 'j.doe@gmail.com',
      password: '123456'
    },
    currency: 'USD',
    merchants: [
      {
        name: 'Bank of America',
        country: 'USA',
      },
      {
        name: 'Amazon.com',
        country: 'USA',
      },
      {
        name: 'United Airlines',
        country: 'USA',
      }
    ],
    currencies: ['USD', 'EUR', 'GBP', 'PLN', 'UAH'],
    categories: {
      incomes: ['Regular', 'Non-Regular'],
      expenses: ['All', 'Uncategorized', 'Benefits', 'Car', 'Equipment', 'Fees', 'Home Office', 'Insurance', 'Interest', 'Labor', 'Maintenance', 'Materials', 'Meal and Entertainment', 'Office Supllies', 'Other', 'Professional Services', 'Rent', 'Taxes', 'Travel', 'Utilities'],
    }
  }
};